### PR TITLE
GPUNetIO: support bonded RoCE interfaces and on DOCA 3.1

### PR DESCRIPTION
**Pull request by foraxe**
## What

Make the existing GPUNETIO Verbs backend usable when RoCE GID and control-plane IPv4 selection must be explicit.

This backend-only change:

- exposes and validates the `gid_index` backend parameter;
- validates explicit OOB IPv4 lookup;
- reports a clear error when DOCA cannot discover an IPv4 address;
- supports DOCA 3.1 `need_dump` and DOCA 3.2+ / later-major `need_mcst`;
- fixes `netif_get_addr` so a missing address is a failure;
- rolls back acquired GPU/AH/device/PD/context resources if late OOB discovery fails.

NIXLBench CLI wiring is intentionally owned by #2173 and is not duplicated here.

## Why

Bonded RoCE and other deployments cannot always derive a usable control-plane address from the RDMA device. They also may require a non-default RoCE GID table entry. The backend must accept those selections directly instead of relying on debug-only environment overrides.

Related: #788, #952, #1954, NVIDIA-DOCA/gpunetio#2, and the earlier broader exploration #1112.

## Current head

```text
branch: nyx/nixl-gpunetio-bonded-device-fix
head:   41e93a3c
```

## Validation

- Full NIXL/GPUNETIO warning-as-error build with CUDA 12.8 and DOCA 3.1.0105: PASS.
- Constructor rollback smoke: repeated failed discovery followed by valid construction/destruction: PASS.
- Cross-endpoint VRAM WRITE, 4 KiB–1 MiB: PASS.
- Cross-endpoint VRAM READ, 4 KiB–1 MiB: PASS.
- No CQE, transfer, or segmentation error in the accepted runs.
- Diff, SPDX, formatting, DCO, and repository checks: PASS.

The transfer reproduction used #2173 only as identical test-time NIXLBench option wiring; it is not part of this branch:

```bash
export ETCD_ENDPOINT='<ETCD_ENDPOINT>'
export BENCHMARK_GROUP='<UNIQUE_GROUP_SHARED_BY_BOTH_ENDPOINTS>'
export RDMA_DEVICE='<ROCE_DEVICE>'
export OOB_INTERFACE='<OOB_INTERFACE>'
export GID_INDEX='<ROCE_GID_INDEX>'

nixlbench \
  --benchmark_group="$BENCHMARK_GROUP" \
  --runtime_type=ETCD \
  --etcd_endpoints="$ETCD_ENDPOINT" \
  --worker_type=nixl \
  --backend=GPUNETIO \
  --device_list="$RDMA_DEVICE" \
  --gpunetio_oob_list="$OOB_INTERFACE" \
  --gpunetio_gid_index="$GID_INDEX" \
  --gpunetio_device_list=0 \
  --initiator_seg_type=VRAM \
  --target_seg_type=VRAM \
  --op_type=WRITE \
  --scheme=pairwise \
  --num_initiator_dev=1 \
  --num_target_dev=1 \
  --start_block_size=4096 \
  --max_block_size=1048576 \
  --num_iter=100 \
  --warmup_iter=10
```

Run the same block on both endpoints with endpoint-local device/interface variables and one shared benchmark group.

## Scope

This PR changes the existing GPUNETIO Verbs backend only. It does not implement NIXLBench flags, request-ring correctness, lifecycle cleanup, peer memory, READ coalescing, or the separate DOCA-RDMA backend.

### CODE REVIEW

**Comment by foraxe** [comment]
Addressed the valid review feedback and followed svc-nixl/clang-format-19 where comments conflicted. 

* The GID default, parseGidIndex naming, and DOCA major-version guard are fixed; 
* the long DOCA call remains  collapsed because that is what CI enforces. 
* The exact 069a3ee2 head was rebuilt and passed the H20 cross-node GPUNETIO Verbs test on mlx5_bond_0/eth0, GID 3, with no CQE or transfer errors. 

The constructor RAII suggestion is deferred as a separate broader change outside this narrow PR.

**Comment by foraxe** [comment]
Complementary validation: the VRAM-to-VRAM READ/get path also passed cross-node on the H20 pods.

- Device: `mlx5_bond_0`
- OOB: `eth0`
- GID: `3`
- Transfer sizes: 4 KiB–1 MiB
- 1 MiB: `12.633446 GB/s`
- No CQE, transfer, or segmentation-fault errors.

**Comment by foraxe** [comment]
Maintainer review ping: this PR remains mergeable and all required repository checks are green. The H20 DOCA 3.1 validation now covers both cross-node VRAM WRITE/put and READ/get over `mlx5_bond_0`, `eth0`, and GID index 3, with no CQE, transfer, or segmentation-fault errors. No scope change is requested; the branch remains the focused bonded-RoCE/GID/DOCA-compatibility fix.

File: src/plugins/gpunetio/gpunetio_backend.cpp [hunk 1]
```diff
@@ -26,6 +26,27 @@
...
+    } catch (const std::exception &) {
+        throw std::invalid_argument("gid_index must be an integer in the range [0, 255]");
+    }
+
+    if (parsed_chars != value.size() || parsed_value < 0 || parsed_value > 255)
+        throw std::invalid_argument("gid_index must be an integer in the range [0, 255]");
+
+    return parsed_value;
+}
+} // namespace
```
[the remark this answers is not in the document]
Comment (foraxe) [reply src/plugins/gpunetio/gpunetio_backend.cpp:103]: Addressed in the current head: the helper is `parseGidIndex`, both control statements use braces, and the call site uses the renamed helper. Current required CI is green.

File: src/plugins/gpunetio/gpunetio_backend.cpp [hunk 2]
```diff
@@ -169,16 +194,24 @@ nixlDocaEngine::nixlDocaEngine(const nixlBackendInitParams *init_params)
...
         struct sockaddr_in *addr_in = (struct sockaddr_in *)&oob_saddr;
         memcpy(ipv4_addr, (uint8_t *)&(addr_in->sin_addr.s_addr), 4);
         NIXL_DEBUG << "Eth IP address " << static_cast<unsigned>(ipv4_addr[0]) << " "
                    << static_cast<unsigned>(ipv4_addr[1]) << " "
                    << static_cast<unsigned>(ipv4_addr[2]) << " "
                    << static_cast<unsigned>(ipv4_addr[3]) << " " << "ifface " << oobdev[0].c_str();
     } else {
-        doca_devinfo_get_ipv4_addr(
+        result = doca_devinfo_get_ipv4_addr(
             doca_dev_as_devinfo(ddev), (uint8_t *)ipv4_addr, DOCA_DEVINFO_IPV4_ADDR_SIZE);
```
[the remark this answers is not in the document]
Comment (foraxe) [reply src/plugins/gpunetio/gpunetio_backend.cpp:263]: This formatting suggestion is outdated and conflicts with the repository's authoritative clang-format-19 check for this exact line. The current collapsed call is the formatter-required form and required CI is green.

File: src/plugins/gpunetio/gpunetio_backend.cpp [hunk 3]
```diff
@@ -169,16 +191,24 @@ nixlDocaEngine::nixlDocaEngine(const nixlBackendInitParams *init_params)
...
+        if (result != DOCA_SUCCESS) {
+            throw std::invalid_argument(
+                "Failed to determine the GPUNETIO IPv4 address; set oob_interface explicitly "
+                "when using a bonded network device");
+        }
```
[the remark this answers is not in the document]
Comment (foraxe) [reply src/plugins/gpunetio/gpunetio_backend.cpp]: Addressed in e3a392c6 with a narrow rollback for the two OOB failure paths added by this PR. Explicit OOB-interface validation now runs before DOCA/RDMA acquisition. If fallback DOCA IPv4 discovery fails after setup, the constructor releases acquired GPU devices, AH attributes, the DOCA device, verbs PD, and verbs context in reverse order before throwing. DOCA 3.1 `werror=true` build passed. A same-process H20 smoke ran one invalid explicit interface, three fallback-discovery failures, then a successful explicit-OOB construction/destruction; it exited cleanly with no GPU or listener residue. Broader pre-existing constructor failure paths remain outside this focused PR.
